name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fmt-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.62
        with:
          components: clippy, rustfmt
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.62
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all-features
      - name: Test
        run: cargo test --all-features --workspace
